name: Update Dictionary
on:
  schedule:
    # per a week
    - cron:  '0 0 * * 0'
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn install
      - name: Try to update dictionary
        run: npm run update
      - name: Tests
        run: npm test
      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          commit-message: "feat(deps): Update dictionary"
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: update-dictionary
          branch-suffix: timestamp
          delete-branch: true
          title: '[Update] Sudashi synonyms dictionary'
          body: |
            New dictionary
            - [SudachiDict](https://github.com/WorksApplications/SudachiDict)
          labels: "Type: dictionary"
          assignees: azu
          reviewers: azu
          draft: false
      - name: Check outputs
        run: |
          echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
