name: automatic release
on:
  push:
    branches:
      - master
    tags:
      - "!*"
    paths:
      - 'package.json'
      - 'sudashi-synonyms-dictionary.json'
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: 'https://registry.npmjs.org'
      - name: install can-npm-publish and dependencies
        run: |
          npm install --global can-npm-publish
          yarn install
      - name: test
        run: npm run test
      - name: check version and add tag
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          REPO: ${{github.repository}}
          COMMIT: ${{github.sha}}
        run: ./release.sh

