name: automatic release
on:
  push:
    branches:
      - master
    tags:
      - "!*"
    paths:
      - 'package.json'
      - 'sudachi-synonyms-dictionary.json'
permissions:
  contents: write
jobs:
  release:
    name: check version, add tag and release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: 'https://registry.npmjs.org'
      - name: install can-npm-publish and dependencies
        run: |
          npm install --global can-npm-publish
          yarn install
      - name: test
        run: npm run test
      - name: Publish
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}} # git tag
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          REPO: ${{github.repository}}
          COMMIT: ${{github.sha}}
        run: ./release.sh

